package com.ubb.backend.DTO;

import lombok.Data;

@Data
public class PlayerDTOAPI {
    private String age;
    private String attacking_crossing;
    private String attacking_finishing;
    private String attacking_heading_accuracy;
    private String attacking_short_passing;
    private String attacking_volleys;
    private String club_contract_valid_until_year;
    private String club_team_id;
    private String defending;
    private String defending_marking_awareness;
    private String defending_sliding_tackle;
    private String defending_standing_tackle;
    private String dribbling;
    private String goalkeeping_diving;
    private String goalkeeping_handling;
    private String goalkeeping_kicking;
    private String goalkeeping_positioning;
    private String goalkeeping_reflexes;
    private String goalkeeping_speed;
    private String height_cm;
    private String mentality_aggression;
    private String mentality_composure;
    private String mentality_interceptions;
    private String mentality_penalties;
    private String mentality_positioning;
    private String mentality_vision;
    private String movement_acceleration;
    private String movement_agility;
    private String movement_balance;
    private String movement_reactions;
    private String movement_sprint_speed;
    private String nationality_name;
    private String overall;
    private String pace;
    private String passing;
    private String physic;
    private String player_id;
    private String player_positions;
    private String player_tags;
    private String player_traits;
    private String potential;
    private String power_jumping;
    private String power_long_shots;
    private String power_shot_power;
    private String power_stamina;
    private String power_strength;
    private String preferred_foot;
    private String shooting;
    private String short_name;
    private String skill_ball_control;
    private String skill_curve;
    private String skill_dribbling;
    private String skill_fk_accuracy;
    private String skill_long_passing;
    private String skill_moves;
    private String value_eur;
    private String weak_foot;
    private String weight_kg;
}
